# Rename file "Application.yml" and add configuration values here, as shown below.

ADMIN_USERNAME: 
ADMIN_PASSWORD: 

ANGELIST_API_URL:

CRUNCHBASE_API_URL:

DEFAULT_EMAIL:

EVENTBRITE_API_URL: 

FACEBOOK_KEY:
FACEBOOK_SECRET: 

MEETUP_API_URL:

PRERENDER_TOKEN:

SECRET_KEY_BASE:

SITE_NAME: 