default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: startupri-dev

test:
  <<: *default
  database: startupri-test

production:
  <<: *default
  host: ec2-23-21-243-117.compute-1.amazonaws.com
  database: d1fsbkefhfp7is
  user: wqzksuunkgrhtv
  password: eV1vxQCG-EFAbrjmo9hat4WR-G
  port: 5432