default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database:

test:
  <<: *default
  database:

production:
  <<: *default
  host: 
  database:
  user:
  password:
  port: