default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: startupri-dev

test:
  <<: *default
  database: startupri-test

production:
  <<: *default
  database: startupri-prod